### ISSUE TITLE
Add config.js to configure the host for real-world hosting

### ISSUE THREAD

**Issue by kelfink** [code4sac/neighborhood-connect#25]
Right now the front end has localhost hard coded.  Need to be configurable

**Comment by ryanmdoyle** [comment]
Ok, the only way I currently know how to handle this is to create a .env.development file within the root where we can set a variable that will be used in development.  In use, it would look like this:
`axios.get('${process.env.REACT_APP_API}/orgs')`

For production, there would be a .env or .env.production with the REACT_APP_API set to the actual endpoint that would get replaced at build time.  C-R-A automatically set the NODE_ENV as 'production' with _react-scripts build_ so it would know to use what's in the .env instead of the env.developent.

If we want to go that route I can make a PR after my #19 gets merged and replace the hard-coded localhost as the example.

We can also set the .env.development to start on another port by default since both our front and back ends are starting on 3000.

**Comment by jordan-paz** [comment]
Would simply creating a variable `baseUrl` and importing it anywhere we make a request be the same thing? Then change the value once we have the actual endpoint?

```
const baseUrl = "http://localhost:3000" 
axios.get('${baseUrl}/orgs')
```

**Comment by ryanmdoyle** [comment]
Yeah, that would work as well, we could just drop it in a config.js.  I supposed I just don't know what the actual endpoint is going to end up being, so I was thinking we might not want it exposed anywhere?

**Comment by ryanmdoyle** [comment]
How about this?
`const apiUrl = (NODE_ENV == 'development')  ? 'http://localhost:3000' : 'the-actual-endpoint'`

**Comment by ryanmdoyle** [comment]
Ok, so I tried out just exporting the url as mentioned above, and we get this error.
![Screen Shot 2019-07-22 at 9 37 40 PM](https://user-images.githubusercontent.com/20651020/61683088-0ee7ff80-acc9-11e9-9664-93fb2a2da0b2.png)

You can go in index.js and change `serviceWorker.unregister();` to `serviceWorker.register();` and the error is gone...but I'm not sure what that does.

**Comment by ryanmdoyle** [comment]
Ok, it looks like the error I was seeing above is only on Firefox, so I switched to Chrome and it's gone.  I made a config.js file with PR #34 

If we want to move over to .env files later on (still not sure why firefox finds a security problem with the current operation) it should be an easy fix.
